export enum AuthErrorCode {
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  REFRESH_IDLE_EXPIRED = 'REFRESH_IDLE_EXPIRED',
  REFRESH_ABSOLUTE_EXPIRED = 'REFRESH_ABSOLUTE_EXPIRED',
  TOKEN_REVOKED = 'TOKEN_REVOKED',
  DEVICE_REVOKED = 'DEVICE_REVOKED',
  TOKEN_REUSE_DETECTED = 'TOKEN_REUSE_DETECTED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
}