# Ansible Inventory File (INI Format)kk
# Alternative to hosts.yml

[app_servers]
app-server-01 ansible_host=89.167.6.46 ansible_user=deployer

[jenkins_servers]
jenkins-server-01 ansible_host=37.27.247.8 ansible_user=root