---
- name: Include pre-deployment tasks
  include_tasks: pre-deploy.yml

- name: Include application setup tasks
  include_tasks: setup-app.yml

- name: Include Docker image build tasks
  include_tasks: build-image.yml
  when: build_image | bool

- name: Include Docker Compose deployment tasks
  include_tasks: deploy-compose.yml

- name: Include post-deployment tasks
  include_tasks: post-deploy.yml