ALTER TABLE order_payments 
ADD COLUMN IF NOT EXISTS payment_method VARCHAR(50),
ADD COLUMN IF NOT EXISTS received_usd DECIMAL(10,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS received_khr DECIMAL(12,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS change_usd DECIMAL(10,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS change_khr DECIMAL(12,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS slip_url VARCHAR(500),
ADD COLUMN IF NOT EXISTS notes TEXT;
