import { DataGenerator } from '../utils/data-generator';
import { SeederHelper } from '../utils/seeder-helper';

export interface CategorySeedData {
  name: string;
  description: string;
}

export interface ProductSeedData {
  productCode: string;
  productName: string;
  barcode: string;
  price: number;
  category?: string;
  description?: string;
  imagePath?: string;
  lowStockThreshold?: number;
  hasExpiry?: boolean;
  status: 'active' | 'inactive';
}

export const categorySeedData: CategorySeedData[] = [
  {
    name: 'Pain & Fever Relief',
    description: 'Analgesics and antipyretics for headache, toothache, muscle pain, and fever reduction.',
  },
  {
    name: 'Antibiotics & Anti-Infectives',
    description: 'Prescription and over-the-counter antibacterial and antimicrobial medications.',
  },
  {
    name: 'Cold, Cough & Allergy',
    description: 'Antihistamines, decongestants, mucolytic cough syrups, and bronchodilators.',
  },
  {
    name: 'Vitamins & Supplements',
    description: 'Essential daily vitamins, minerals, immune boosters, and dietary health supplements.',
  },
  {
    name: 'Digestive & GI Health',
    description: 'Antacids, proton pump acid blockers, antidiarrheals, and ORS electrolyte fluids.',
  },
  {
    name: 'Cardiovascular & Diabetes',
    description: 'Chronic care therapeutics for hypertension, blood glucose, and cholesterol management.',
  },
  {
    name: 'First Aid & Medical Supplies',
    description: 'Sterile gauze, antiseptic wound cleansers, surgical tape, bandages, and diagnostic tools.',
  },
  {
    name: 'Topical & Skincare Remedies',
    description: 'Medicated creams, topical antifungal ointments, cooling gels, eye drops, and balms.',
  },
];

export const productSeedData: ProductSeedData[] = [
  // --- 1. Pain & Fever Relief ---
  {
    productCode: 'MED-0001',
    productName: 'Paracetamol 500mg (100 Tablets)',
    barcode: '884000100001',
    price: 3.50,
    category: 'Pain & Fever Relief',
    description: 'Effective temporary relief of fever, headache, toothache, and general aches.',
    lowStockThreshold: 20,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0002',
    productName: 'Ibuprofen 400mg (50 Softgels)',
    barcode: '884000100002',
    price: 5.20,
    category: 'Pain & Fever Relief',
    description: 'Non-steroidal anti-inflammatory drug (NSAID) for fever, backache, and inflammation.',
    lowStockThreshold: 15,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0003',
    productName: 'Aspirin 81mg Low Dose (100 Tablets)',
    barcode: '884000100003',
    price: 4.80,
    category: 'Pain & Fever Relief',
    description: 'Low-dose acetylsalicylic acid for pain relief and cardiovascular therapy.',
    lowStockThreshold: 10,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0004',
    productName: 'Mefenamic Acid 500mg (Ponstan 20s)',
    barcode: '884000100004',
    price: 6.50,
    category: 'Pain & Fever Relief',
    description: 'Fast relief of acute pain, dental pain, and menstrual discomfort.',
    lowStockThreshold: 12,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0005',
    productName: 'Tramadol HCl 50mg (20 Capsules)',
    barcode: '884000100005',
    price: 8.90,
    category: 'Pain & Fever Relief',
    description: 'Centrally acting analgesic for moderate to severe pain management.',
    lowStockThreshold: 8,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0006',
    productName: 'Voltaren Gel 1% (Diclofenac 20g)',
    barcode: '884000100006',
    price: 7.20,
    category: 'Pain & Fever Relief',
    description: 'Topical anti-inflammatory gel for localized muscle and joint pain.',
    lowStockThreshold: 10,
    hasExpiry: true,
    status: 'active',
  },

  // --- 2. Antibiotics & Anti-Infectives ---
  {
    productCode: 'MED-0007',
    productName: 'Amoxicillin 500mg (20 Capsules)',
    barcode: '884000100007',
    price: 4.50,
    category: 'Antibiotics & Anti-Infectives',
    description: 'Broad-spectrum penicillin antibiotic for ear, throat, and urinary tract infections.',
    lowStockThreshold: 25,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0008',
    productName: 'Azithromycin 250mg (6 Film Tablets)',
    barcode: '884000100008',
    price: 9.50,
    category: 'Antibiotics & Anti-Infectives',
    description: 'Macrolide antibiotic for upper/lower respiratory tract and skin infections.',
    lowStockThreshold: 15,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0009',
    productName: 'Ciprofloxacin 500mg (10 Tablets)',
    barcode: '884000100009',
    price: 6.80,
    category: 'Antibiotics & Anti-Infectives',
    description: 'Fluoroquinolone antibiotic for bacterial infections of gastrointestinal and urinary tracts.',
    lowStockThreshold: 10,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0010',
    productName: 'Cefalexin 500mg (20 Capsules)',
    barcode: '884000100010',
    price: 7.50,
    category: 'Antibiotics & Anti-Infectives',
    description: 'First-generation cephalosporin antibiotic for respiratory and soft tissue infections.',
    lowStockThreshold: 12,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0011',
    productName: 'Augmentin 625mg (Amoxicillin + Clavulanate 14s)',
    barcode: '884000100011',
    price: 14.50,
    category: 'Antibiotics & Anti-Infectives',
    description: 'Potent combination antibiotic resistant to beta-lactamase producing bacteria.',
    lowStockThreshold: 10,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0012',
    productName: 'Metronidazole 400mg (20 Tablets)',
    barcode: '884000100012',
    price: 3.80,
    category: 'Antibiotics & Anti-Infectives',
    description: 'Synthetic antimicrobial and antiprotozoal agent for anaerobic infections.',
    lowStockThreshold: 15,
    hasExpiry: true,
    status: 'active',
  },

  // --- 3. Cold, Cough & Allergy ---
  {
    productCode: 'MED-0013',
    productName: 'Cetirizine HCl 10mg (30 Tablets)',
    barcode: '884000100013',
    price: 4.20,
    category: 'Cold, Cough & Allergy',
    description: 'Non-drowsy 24-hour antihistamine for allergic rhinitis, sneezing, and hives.',
    lowStockThreshold: 20,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0014',
    productName: 'Loratadine 10mg (Claritin 10s)',
    barcode: '884000100014',
    price: 5.00,
    category: 'Cold, Cough & Allergy',
    description: 'Long-acting antihistamine for hay fever, watery eyes, and runny nose.',
    lowStockThreshold: 15,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0015',
    productName: 'Decolgen Forte (10 Caplets)',
    barcode: '884000100015',
    price: 2.80,
    category: 'Cold, Cough & Allergy',
    description: 'Multi-symptom cold medication relieving congestion, fever, and headache.',
    lowStockThreshold: 25,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0016',
    productName: 'Bromhexine HCl 8mg Syrup (100ml)',
    barcode: '884000100016',
    price: 4.60,
    category: 'Cold, Cough & Allergy',
    description: 'Mucolytic elixir syrup for thinning phlegm in productive chesty coughs.',
    lowStockThreshold: 12,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0017',
    productName: 'Dextromethorphan 15mg (20 Lozenges)',
    barcode: '884000100017',
    price: 3.40,
    category: 'Cold, Cough & Allergy',
    description: 'Cough suppressant lozenges for temporary relief of tickly dry cough.',
    lowStockThreshold: 15,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0018',
    productName: 'Otrivin Adult Nasal Spray 0.1% (10ml)',
    barcode: '884000100018',
    price: 6.20,
    category: 'Cold, Cough & Allergy',
    description: 'Fast-acting nasal decongestant spray relieving blocked nasal passages.',
    lowStockThreshold: 10,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0019',
    productName: 'Salbutamol Inhaler 100mcg (Ventolin 200 Doses)',
    barcode: '884000100019',
    price: 8.50,
    category: 'Cold, Cough & Allergy',
    description: 'Short-acting beta2-agonist bronchodilator for relief of acute asthma attacks.',
    lowStockThreshold: 10,
    hasExpiry: true,
    status: 'active',
  },

  // --- 4. Vitamins & Supplements ---
  {
    productCode: 'MED-0020',
    productName: 'Vitamin C 1000mg Effervescent (20s)',
    barcode: '884000100020',
    price: 5.90,
    category: 'Vitamins & Supplements',
    description: 'Effervescent immune booster tablets enriched with Zinc.',
    lowStockThreshold: 20,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0021',
    productName: 'Multivitamin & Minerals Complex (60 Caps)',
    barcode: '884000100021',
    price: 11.50,
    category: 'Vitamins & Supplements',
    description: 'Comprehensive daily essential vitamin supplement for overall vitality.',
    lowStockThreshold: 15,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0022',
    productName: 'Omega-3 Fish Oil 1000mg (100 Softgels)',
    barcode: '884000100022',
    price: 13.80,
    category: 'Vitamins & Supplements',
    description: 'Rich source of EPA and DHA fatty acids supporting cardiovascular and joint health.',
    lowStockThreshold: 12,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0023',
    productName: 'Calcium + Vitamin D3 500mg (60 Chewables)',
    barcode: '884000100023',
    price: 8.20,
    category: 'Vitamins & Supplements',
    description: 'Dietary supplement promoting strong bones and optimal calcium absorption.',
    lowStockThreshold: 15,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0024',
    productName: 'Zinc Sulfate 50mg (30 Tablets)',
    barcode: '884000100024',
    price: 4.90,
    category: 'Vitamins & Supplements',
    description: 'Essential trace element supplement for immune defense and wound healing.',
    lowStockThreshold: 10,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0025',
    productName: 'Vitamin B-Complex High Potency (100s)',
    barcode: '884000100025',
    price: 9.10,
    category: 'Vitamins & Supplements',
    description: 'Supports nervous system function, cell metabolism, and energy conversion.',
    lowStockThreshold: 10,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0026',
    productName: 'Ferrous Sulfate 300mg Iron (30 Tablets)',
    barcode: '884000100026',
    price: 3.90,
    category: 'Vitamins & Supplements',
    description: 'Iron supplement for prevention and treatment of iron-deficiency anemia.',
    lowStockThreshold: 15,
    hasExpiry: true,
    status: 'active',
  },

  // --- 5. Digestive & GI Health ---
  {
    productCode: 'MED-0027',
    productName: 'Omeprazole 20mg (Gasec 14 Caps)',
    barcode: '884000100027',
    price: 7.80,
    category: 'Digestive & GI Health',
    description: 'Proton pump inhibitor reducing gastric acid secretion for ulcer and reflux therapy.',
    lowStockThreshold: 15,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0028',
    productName: 'Gaviscon Double Action Suspension (150ml)',
    barcode: '884000100028',
    price: 8.90,
    category: 'Digestive & GI Health',
    description: 'Dual action raft-forming antacid for fast relief from indigestion and acid reflux.',
    lowStockThreshold: 10,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0029',
    productName: 'Loperamide HCl 2mg (Imodium 10s)',
    barcode: '884000100029',
    price: 3.50,
    category: 'Digestive & GI Health',
    description: 'Antidiarrheal agent providing rapid relief of acute non-specific diarrhea.',
    lowStockThreshold: 20,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0030',
    productName: 'Oral Rehydration Salts (ORS 10 Sachets)',
    barcode: '884000100030',
    price: 3.00,
    category: 'Digestive & GI Health',
    description: 'Balanced electrolyte powder formula for restoring fluids lost during dehydration.',
    lowStockThreshold: 30,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0031',
    productName: 'Buscopan 10mg (Hyoscine 20 Tablets)',
    barcode: '884000100031',
    price: 6.10,
    category: 'Digestive & GI Health',
    description: 'Antispasmodic medication targeting intestinal, stomach, and bladder cramps.',
    lowStockThreshold: 12,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0032',
    productName: 'Activated Charcoal 250mg (20 Caps)',
    barcode: '884000100032',
    price: 4.40,
    category: 'Digestive & GI Health',
    description: 'Natural adsorbent capsules for abdominal distension, gas, and indigestion.',
    lowStockThreshold: 15,
    hasExpiry: true,
    status: 'active',
  },

  // --- 6. Cardiovascular & Diabetes ---
  {
    productCode: 'MED-0033',
    productName: 'Metformin HCl 500mg (100 Tablets)',
    barcode: '884000100033',
    price: 8.50,
    category: 'Cardiovascular & Diabetes',
    description: 'First-line oral biguanide antihyperglycemic medication for Type 2 diabetes.',
    lowStockThreshold: 25,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0034',
    productName: 'Amlodipine 5mg (Norvasc 30 Tablets)',
    barcode: '884000100034',
    price: 9.20,
    category: 'Cardiovascular & Diabetes',
    description: 'Dihydropyridine calcium channel blocker for treatment of hypertension and angina.',
    lowStockThreshold: 20,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0035',
    productName: 'Losartan Potassium 50mg (30 Tablets)',
    barcode: '884000100035',
    price: 10.40,
    category: 'Cardiovascular & Diabetes',
    description: 'Angiotensin II receptor antagonist (ARB) for blood pressure control.',
    lowStockThreshold: 15,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0036',
    productName: 'Atorvastatin 20mg (Lipitor 30 Tablets)',
    barcode: '884000100036',
    price: 14.90,
    category: 'Cardiovascular & Diabetes',
    description: 'HMG-CoA reductase inhibitor statin lowering blood LDL cholesterol levels.',
    lowStockThreshold: 15,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0037',
    productName: 'Glimepiride 2mg (30 Tablets)',
    barcode: '884000100037',
    price: 7.30,
    category: 'Cardiovascular & Diabetes',
    description: 'Second-generation sulfonylurea stimulating insulin secretion in diabetic care.',
    lowStockThreshold: 10,
    hasExpiry: true,
    status: 'active',
  },

  // --- 7. First Aid & Medical Supplies ---
  {
    productCode: 'MED-0038',
    productName: 'Digital Infrared Forehead Thermometer',
    barcode: '884000100038',
    price: 24.50,
    category: 'First Aid & Medical Supplies',
    description: 'Non-contact clinical grade infrared thermometer with LCD backlight display.',
    lowStockThreshold: 5,
    hasExpiry: false,
    status: 'active',
  },
  {
    productCode: 'MED-0039',
    productName: 'Sterile Gauze Pads 4x4 in (10 Packs)',
    barcode: '884000100039',
    price: 3.60,
    category: 'First Aid & Medical Supplies',
    description: 'Highly absorbent 8-ply sterile cotton gauze sponges for wound dressing.',
    lowStockThreshold: 20,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0040',
    productName: 'Betadine Antiseptic Solution 10% (30ml)',
    barcode: '884000100040',
    price: 3.20,
    category: 'First Aid & Medical Supplies',
    description: 'Microbicidal povidone-iodine solution for topical wound infection prevention.',
    lowStockThreshold: 15,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0041',
    productName: 'Medical Adhesive Tape 1 inch (Roll)',
    barcode: '884000100041',
    price: 1.80,
    category: 'First Aid & Medical Supplies',
    description: 'Hypoallergenic surgical paper tape for securing bandages and dressings.',
    lowStockThreshold: 25,
    hasExpiry: false,
    status: 'active',
  },
  {
    productCode: 'MED-0042',
    productName: 'Isopropyl Alcohol 70% Spray (500ml)',
    barcode: '884000100042',
    price: 4.10,
    category: 'First Aid & Medical Supplies',
    description: 'First aid antiseptic alcohol spray for skin cleansing and surface disinfection.',
    lowStockThreshold: 20,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0043',
    productName: 'Elastic Crepe Bandage 7.5cm x 4.5m',
    barcode: '884000100043',
    price: 2.50,
    category: 'First Aid & Medical Supplies',
    description: 'Reusable compression support bandage for sprains, strains, and joint wrapping.',
    lowStockThreshold: 15,
    hasExpiry: false,
    status: 'active',
  },
  {
    productCode: 'MED-0044',
    productName: 'Adhesive Bandages Waterproof (50s Pack)',
    barcode: '884000100044',
    price: 3.80,
    category: 'First Aid & Medical Supplies',
    description: 'Assorted sterile waterproof plaster strips for protection of minor cuts and scrapes.',
    lowStockThreshold: 25,
    hasExpiry: true,
    status: 'active',
  },

  // --- 8. Topical & Skincare Remedies ---
  {
    productCode: 'MED-0045',
    productName: 'Hydrocortisone Cream 1% (15g)',
    barcode: '884000100045',
    price: 4.70,
    category: 'Topical & Skincare Remedies',
    description: 'Mild topical corticosteroid soothing skin rashes, insect bites, and eczema itching.',
    lowStockThreshold: 10,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0046',
    productName: 'Clotrimazole Antifungal Cream 1% (20g)',
    barcode: '884000100046',
    price: 5.30,
    category: 'Topical & Skincare Remedies',
    description: 'Topical broad-spectrum antifungal cream treating athlete foot and ringworm.',
    lowStockThreshold: 12,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0047',
    productName: 'Burn Shield Cooling Gel (50g Tube)',
    barcode: '884000100047',
    price: 6.80,
    category: 'Topical & Skincare Remedies',
    description: 'Emergency hydrogel providing immediate cooling relief and pain soothing for minor burns.',
    lowStockThreshold: 8,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0048',
    productName: 'Pure Petroleum Jelly (Vaseline 100g)',
    barcode: '884000100048',
    price: 3.10,
    category: 'Topical & Skincare Remedies',
    description: 'Protective ointment locking in moisture to restore dry, cracked skin.',
    lowStockThreshold: 20,
    hasExpiry: false,
    status: 'active',
  },
  {
    productCode: 'MED-0049',
    productName: 'Lubricating Eye Drops (15ml Bottle)',
    barcode: '884000100049',
    price: 5.50,
    category: 'Topical & Skincare Remedies',
    description: 'Artificial tear drops comforting dry, strained, and irritated eyes.',
    lowStockThreshold: 15,
    hasExpiry: true,
    status: 'active',
  },
  {
    productCode: 'MED-0050',
    productName: 'Tiger Balm Ointment Red (19.4g)',
    barcode: '884000100050',
    price: 4.90,
    category: 'Topical & Skincare Remedies',
    description: 'Herbal rub providing fast warmth and pain relief for aching muscles and insect stings.',
    lowStockThreshold: 15,
    hasExpiry: true,
    status: 'inactive',
  },
];

